version: '3.7'

networks:
  services:
    ipam:
      config:
        - subnet: ${SUBNET}

services:
  #
  # Webserver
  #
  webserver:
    image: indy-node
    build:
      context: .
      dockerfile: pool.dockerfile
    command: 'bash -c ''./scripts/start_webserver.sh'''
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - HOST=${HOSTIP}
      - RUST_LOG=${RUST_LOG}
    networks:
      services:
        ipv4_address: ${HOSTIP}
    ports:
      - 9000:8000
    depends_on:
      - node1
      - node2
      - node3
      - node4
    volumes:
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - node1-data:/home/indy/.mnt/node1
      - node2-data:/home/indy/.mnt/node2
      - node3-data:/home/indy/.mnt/node3
      - node4-data:/home/indy/.mnt/node4

  #
  # Nodes
  #
  node1:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 1'''
    networks:
      services:
        ipv4_address: ${IP1}
    ports:
      - 9701:9701
      - 9702:9702
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node1-data:/home/indy/ledger

  node2:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 2'''
    networks:
      services:
        ipv4_address: ${IP2}
    ports:
      - 9703:9703
      - 9704:9704
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node2-data:/home/indy/ledger

  node3:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 3'''
    networks:
      services:
        ipv4_address: ${IP3}
    ports:
      - 9705:9705
      - 9706:9706
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node3-data:/home/indy/ledger

  node4:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 4'''
    networks:
      services:
        ipv4_address: ${IP4}
    ports:
      - 9707:9707
      - 9708:9708
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node4-data:/home/indy/ledger

volumes:
  webserver-cli:
  node1-data:
  node2-data:
  node3-data:
  node4-data: