version: '3.7'

networks:
  services:
    ipam:
      config:
        - subnet: ${SUBNET}

services:
  #
  # Webserver
  #
  webserver:
    image: indy-node
    build:
      context: .
      dockerfile: pool.dockerfile
    command: 'bash -c ''./scripts/start_webserver.sh'''
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - NODE1_PORT=${NODE1_PORT}
      - NODE2_PORT=${NODE2_PORT}
      - NODE3_PORT=${NODE3_PORT}
      - NODE4_PORT=${NODE4_PORT}
      - NODE1_CLIENT_PORT=${NODE1_CLIENT_PORT}
      - NODE2_CLIENT_PORT=${NODE2_CLIENT_PORT}
      - NODE3_CLIENT_PORT=${NODE3_CLIENT_PORT}
      - NODE4_CLIENT_PORT=${NODE4_CLIENT_PORT}
      - HOST=${HOSTIP}
      - RUST_LOG=${RUST_LOG}
    networks:
      services:
        ipv4_address: ${HOSTIP}
    ports:
      - 8000:8000
    depends_on:
      - node1
      - node2
      - node3
      - node4
    volumes:
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - node1-data:/home/indy/.mnt/node1
      - node2-data:/home/indy/.mnt/node2
      - node3-data:/home/indy/.mnt/node3
      - node4-data:/home/indy/.mnt/node4
  #
  # Nodes
  #
  node1:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 1'''
    networks:
      services:
        ipv4_address: ${IP1}
    ports:
      - ${NODE1_PORT}:${NODE1_PORT}
      - ${NODE1_CLIENT_PORT}:${NODE1_CLIENT_PORT}
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - RUST_LOG=${RUST_LOG}
      - NODE_PORT=${NODE1_PORT}
      - NODE_CLIENT_PORT=${NODE1_CLIENT_PORT}
      - NODE1_PORT=${NODE1_PORT}
      - NODE2_PORT=${NODE2_PORT}
      - NODE3_PORT=${NODE3_PORT}
      - NODE4_PORT=${NODE4_PORT}
      - NODE1_CLIENT_PORT=${NODE1_CLIENT_PORT}
      - NODE2_CLIENT_PORT=${NODE2_CLIENT_PORT}
      - NODE3_CLIENT_PORT=${NODE3_CLIENT_PORT}
      - NODE4_CLIENT_PORT=${NODE4_CLIENT_PORT}
    volumes:
      - node1-data:/home/indy/ledger

  node2:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 2'''
    networks:
      services:
        ipv4_address: ${IP2}
    ports:
      - ${NODE2_PORT}:${NODE2_PORT}
      - ${NODE2_CLIENT_PORT}:${NODE2_CLIENT_PORT}
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - RUST_LOG=${RUST_LOG}
      - NODE_PORT=${NODE2_PORT}
      - NODE_CLIENT_PORT=${NODE2_CLIENT_PORT}
      - NODE1_PORT=${NODE1_PORT}
      - NODE2_PORT=${NODE2_PORT}
      - NODE3_PORT=${NODE3_PORT}
      - NODE4_PORT=${NODE4_PORT}
      - NODE1_CLIENT_PORT=${NODE1_CLIENT_PORT}
      - NODE2_CLIENT_PORT=${NODE2_CLIENT_PORT}
      - NODE3_CLIENT_PORT=${NODE3_CLIENT_PORT}
      - NODE4_CLIENT_PORT=${NODE4_CLIENT_PORT}
    volumes:
      - node2-data:/home/indy/ledger

  node3:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 3'''
    networks:
      services:
        ipv4_address: ${IP3}
    ports:
      - ${NODE3_PORT}:${NODE3_PORT}
      - ${NODE3_CLIENT_PORT}:${NODE3_CLIENT_PORT}
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - RUST_LOG=${RUST_LOG}
      - NODE_PORT=${NODE3_PORT}
      - NODE_CLIENT_PORT=${NODE3_CLIENT_PORT}
      - NODE1_PORT=${NODE1_PORT}
      - NODE2_PORT=${NODE2_PORT}
      - NODE3_PORT=${NODE3_PORT}
      - NODE4_PORT=${NODE4_PORT}
      - NODE1_CLIENT_PORT=${NODE1_CLIENT_PORT}
      - NODE2_CLIENT_PORT=${NODE2_CLIENT_PORT}
      - NODE3_CLIENT_PORT=${NODE3_CLIENT_PORT}
      - NODE4_CLIENT_PORT=${NODE4_CLIENT_PORT}
    volumes:
      - node3-data:/home/indy/ledger

  node4:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 4'''
    networks:
      services:
        ipv4_address: ${IP4}
    ports:
      - ${NODE4_PORT}:${NODE4_PORT}
      - ${NODE4_CLIENT_PORT}:${NODE4_CLIENT_PORT}
    environment:
      - IPS=${IP1},${IP2},${IP3},${IP4}
      - RUST_LOG=${RUST_LOG}
      - NODE_PORT=${NODE4_PORT}
      - NODE_CLIENT_PORT=${NODE4_CLIENT_PORT}
      - NODE1_PORT=${NODE1_PORT}
      - NODE2_PORT=${NODE2_PORT}
      - NODE3_PORT=${NODE3_PORT}
      - NODE4_PORT=${NODE4_PORT}
      - NODE1_CLIENT_PORT=${NODE1_CLIENT_PORT}
      - NODE2_CLIENT_PORT=${NODE2_CLIENT_PORT}
      - NODE3_CLIENT_PORT=${NODE3_CLIENT_PORT}
      - NODE4_CLIENT_PORT=${NODE4_CLIENT_PORT}
    volumes:
      - node4-data:/home/indy/ledger

volumes:
  webserver-cli:
  node1-data:
  node2-data:
  node3-data:
  node4-data: